# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',  url: 'about'}
- {name: '3D Printing',  url: '3dprinting'}
- {name: 'Painting',  url: 'painting'}
- {name: 'Gallery',  url: 'gallery'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link:   'https://www.facebook.com/alexmeeky'}
- {icon: 'instagram', link:  'https://www.instagram.com/emeekcsquared/'}
- {icon: 'envelope', link:   'mailto:alexander.meek98@gmail.com'}

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Last Updated on '
